xsd/parse.go, xsd/testdata/mixed.xsd, xsd/xsd.go, xsd/xsd_test.go, xsdgen/testdata/mixed-complex.xsd, xsdgen/xsdgen.go, xsdgen/xsdgen_test.go
This should fix issue #9, in which xsdgen fails to generate proper Go type declarations for types that restrict another type with a mixed content model. In other words, given the following type
<complexType name="Number">
<simpleContent>
<extension base="double">
<attribute name="precision" type="int" />
</extension>
</simpleContent>
</complexType>
Example usage:
<Number precision=3>1.024</Number>
We obviously care about what comes between the <Number> tags. However for types derived from `Number`, xsdgen would only generate the proper type declarations for types that were derived by extension. This fixes that issue, and introduces the "mixed" property from the XML schema, and propagates it to all derived types following (mostly) the rules of the XML schema spec.
=> Don't miss char data when restricting a mixed type

wsdlgen/wsdlgen_test.go, xsdgen/example_test.go, xsdgen/xsdgen.go
The `xsdDateTime` couldn't be marshalled in XML, however it works if I put it into a slice (have no idea why).
Anyway, this fix should work both on object and pointer receiver.
=> marshal xsdDateTime object

xmltree/marshal.go, xmltree/xmltree.go, xmltree/xmltree_test.go
Previously the `xmlns` attributes would end up in both `Element.Scope.NS` and in `Element.StartElement.Attr`, so when you called `Marshal(root)`, you would get duplicates, which causes `encoding/xml.Unmarshal` to error.
Edit:
I've also added a commit to resolve prefixes on attributes. Without this, I was seeing attributes like:
```
<p:sldId id="256" http://schemas.openxmlformats.org/officeDocument/2006/relationships:id="rId2"></p:sldId>
```
instead of:
```
<p:sldId id="256" r:id="rId2"></p:sldId>
```
I wasn't sure of a good way to write a test for this, but can have more of a think about that if you prefer.
=> Fix duplication of xmlns attributes when marshalling

internal/gen/gen.go, xsdgen/builtin.go, xsdgen/config.go, xsdgen/example_test.go, xsdgen/testdata/base64.xsd, xsdgen/xsdgen.go
Work-in-progress. For non-trivial builtins like dateTime, gDay,
base64Binary, etc, previously we would generate a non-exported type
declaration with the corresponding `UnmarshalText`/`MarshalText`
declarations. For example,
type xsdDate time.Time
func (t *xsdDate) UnmarshalText(text []byte) error {
return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
type Library struct {
Book      []Book  `xml:"http://www.example.com/ book"`
Title     string  `xml:"http://www.example.com/ title"`
Published xsdDate `xml:"http://www.example.com/ published"`
Author    string  `xml:"http://www.example.com/ author"`
}
The problem with this approach is that it exposes a private type in
an exported struct. It's not clear that the `Published` field above can
be converted to a `time.Time` type, and it's …
=> Change xml unmarshal strategy for non-trivial builtins

xmltree/compare.go, xsdgen/_testgen/testgen.go, xsdgen/bindata_gen_test.go, xsdgen/books_gen_test.go, xsdgen/testdata/bindata.xml, xsdgen/testdata/bindata.xsd, xsdgen/testdata/books.xml, xsdgen/testdata/books.xsd, xsdgen/xsdgen_test.go
To add a new test, create two files in xsdgen/testdata:
- <name>.xsd , containing a single XML schema document.
- <name>.xml, containing sample data conforming to the schema.
Then run 'go generate' in the xsdgen directory. The file name should
be a valid Go identifier, and the schema should list as a top-level element
every element in the sample data.
The file <name>_gen_test.go will be generated, containing type declarations
from the schema, and a unit test function, Test<Name>, that does the following:
- Declares a top-level Document struct containing each element described
in the schema.
- Unmarshals the sample file into said struct.
- Marshals said struct back into XML.
- Confirms that the output XML is equivalent to the input XML.
The `xmltree.Equal` method was added for this …
=> Add marshal/unmarshal tests for generated Go code.

xmltree/marshal.go, xmltree/xmltree.go
* Fix a regression in `diffScope` function that only removed first common xmlns element.
* Sort xmlns declarations at each level, to increase chance of similarities
=> Reduce redundant xmlns declarations

xsd/parse.go, xsd/testdata/Anonymous.json
Generated names for anonymous types are ugly, so we should avoid them
when we can.
Helps with (but does not resolve) #14
=> Name anonymous types after containing elements/attributes

internal/gen/gen.go, wsdlgen/cli.go, xsdgen/cli.go
On Windows I was getting an error for invalid filename in this call. I'm under the impression that this error may not happen on Linux.
=> fix imports.Process call

xsd/parse.go, xsd/testdata/AttributeGroup.json, xsd/testdata/AttributeGroup.xsd
=> Don't overwrite linked objects when flattening references.

xsd/parse.go, xsd/testdata/ComplexType.xsd, xsd/xsd_test.go, xsdgen/example_test.go
The `xsd` package already ensures that every type has a name, generating a name if needed. This change ensures all types are declared as direct children of the `<schema>` element. This makes subsequent transforms simpler and less error prone, and should address #41, where nested types were inadvertently duplicated when flattening document references.
=> Unnest anonymous types

xsd/parse.go
This happens because on range, the length is evaluated once, but inside the loop a item can be removed.
=> xsd: fix index out of bounds on range

xsd/parse.go, xsd/testdata/EmptyComplexType.json, xsd/testdata/EmptyComplexType.xsd
In the issue reported in #50 the `xsd` package produced an invalid Type when given an empty ComplexType declaration. This should fix that issue, and hopefully make the complex shorthand expansion code a little more robust.
=> ensure empty complex types derive from AnyType

wsdl/wsdl.go, wsdlgen/wsdlgen.go, wsdlgen/wsdlgen_test.go, xsd/parse.go, xsdgen/cli.go, xsdgen/xsdgen.go
This addresses #14. Now all parsed `xsd.Schema` have an additional entry
in their `Types` map: `tns:_self`. This is a `*ComplexType` with all
top-level elements in its `Elements` list. The `wsdlgen` package has
been updated to lookup the type of elements named in a `wsdl:part` field.
=> wsdlgen: wsdl:part with element attributes.

xsdgen/config.go
We may be able to remove UseFieldNames altogether, since the
xsd package already has this behavior. However, this is a smaller
change and fixes #56 .
=> Avoid duplicate types resulting from UseFieldNames option.

xsdgen/example_test.go, xsdgen/xsdgen.go
More often than not, a complex type is derived from another
complex type, and during the code gen process, it is simplified
to derive from anyType, and there are no additional types to pull
in.
This fixes issues with missing types for schema that meet the
following criteria:
* There are complexTypes derived from simpleTypes (using simpleContent).
* The simpleTypes are not used anywhere else.
* The simpleTypes are simplified to builtin types because they are
not interesting enough.
=> Flatten and generate code for parents of complex types.

README.md, cmd/wsdlgen/wsdlgen.go, cmd/xsdgen/doc.go, cmd/xsdparse/xsdparse.go, gentests/gentest.go, internal/commandline/cli.go, internal/dependency/graph.go, internal/gen/gen.go, wsdl/wsdl.go, wsdlgen/wsdlgen.go
* Note import paths with go get in README.
* Put import comment restrictions on package lacking them.
Please take a look.
Fixes #69.
=> all: clarify import locations

.travis.yml, README.md
The use of the golang.org/x/imports package depends on the type aliases feature introduced in go1.9.
=> Remove support for Go versions before 1.9

gentests/books/books.xml, gentests/books/books.xsd, gentests/books/books_test.go, xsd/parse.go, xsdgen/example_test.go, xsdgen/xsdgen.go
This attempts to address https://github.com/droyo/go-xml/issues/80
It seemed to do the right thing on my WSDL files, but I'm not 100% certain the behaviour is perfect.
I've updated the test cases and generated code to match the new output, but I don't know if it's correct.
=>  Pass namespace through to attribute metadata 

xmltree/example_test.go, xmltree/marshal.go
To be able to use and unmarshal the XML generated  by MarshalIndent it's
not possible to have leading or trailing whitespaces for a given tag
since this will be kept. Fixes #82
=> Remove unwanted whitespaces from MarshalIndent output.

xsd/parse.go, xsdgen/example_test.go
Fixes issue where elements within a complexType took the namespace of the parent schema instead of the namespace of the element.
=> Fix NS tags on linked complexTypes

xsd/parse.go, xsdgen/xsdgen.go
Reverting droyo/go-xml#93 until we can fix #101
=> Revert "Fix sequence order, optional structs as pointers, elements inside choice are optional"

xsdgen/xsdgen.go
It returns the elements extended in the correct order.
=> add order to extensions

xsd/parse.go
Reason:
The name of the _anon fields is repeated and overwrite because of different namespaces.
Solution:
The counter is not reseted when changes the root
=> fix anon number to not be repeated because of different namespaces

xsd/parse.go
DateTime as valid type when parsing with simple restriction.
=> Issue #114.

xsdgen/config.go, xsdgen/example_test.go
Fixes: #113
This PR fixes the method xsdDateTime.MarshalText by adding the
support for considering the timezone offset when marshalling. Previously
it dropped the offset.
Modified the example_test as well.
As an addition, I removed the dead code for `*Config`'s method `errorf`.
=> Fix xsdDateTime.MarshalText method for considering timezone offset when marshalling

xsd/builtin.go
commit d7de88e1dfd94ebd3b0562f49285b7809286a360 introduce anySimpleType
but did not update the code which parsed builtins to consider it.
see #117
=> Fix error parsing AnySimpleType

wsdl/wsdl.go, wsdlgen/cli.go, wsdlgen/config.go, xsd/parse.go, xsd/xsd.go, xsdgen/cli.go, xsdgen/config.go, xsdgen/xsdgen.go
Tools used: go vet, staticcheck, golangci-lint
Fixed some basic, small errors such as:
1. Remove unnecessary use of fmt.Sprintf when arg is already a string
2. Check errors
3. Remove dead code blocks
4. Remove unreachable code
5. Don't put punctuation or new after error messages (in packages)
Sample output from `golangci-lint`, `staticcheck`:
* `staticcheck`:
```
wsdl/wsdl.go:59:25: the argument is already a string, there's no need to use fmt.Sprintf (S1025)
wsdl/wsdl.go:61:9: the argument is already a string, there's no need to use fmt.Sprintf (S1025)
wsdlgen/cli.go:44:10: error strings should not be capitalized (ST1005)
wsdlgen/cli.go:44:10: error strings should not end with punctuation or a newline (ST1005)
wsdlgen/config.go:42:20: func (*Config).publicName is unused (U1000) …
```
=> Fix warnings/errors reported by static code analysers

xsdgen/cli.go, xsdgen/config.go
this reorganizes the logic around reading files such
that reading xsd files can recursively follow import
directives, automatically adding imported files into
the list of xsd files being parsed.
this removes the need to manually discovery
which combination of xsd files might be needed
in order to have a complete/parsable schema
=> optionally follow imports in xsd files

xsd/parse.go, xsd/xsd.go
- Added support for `totalDigits` restriction
- Fixes for `maxLength` and `length` restrictions - previously `length` was being parsed as `maxLength`, have now added `length` as a separate restriction and updated `maxLength`
- Updated `min/maxIn/Exclusive` to support linked types - since the base of these is unknown, attempt to parse dates and then decimal.
=> XSD restriction enhancements
